name: Android Deploy to Play Store (Native Android)

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # ----------------------------------------------------
      # 1. CHECKOUT CODE
      # ----------------------------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ----------------------------------------------------
      # 2. SETUP JAVA & GRADLE
      # ----------------------------------------------------
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      # ----------------------------------------------------
      # 3. RESTORE SIGNING FILES FROM SECRETS
      # ----------------------------------------------------
      - name: Decode Keystore File
        run: |
          mkdir -p app
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/upload-keystore.jks

      - name: Decode key.properties File
        run: |
          echo "${{ secrets.KEY_PROPERTIES_BASE64 }}" | base64 --decode > key.properties

      # ----------------------------------------------------
      # 4. BUILD SIGNED RELEASE AAB
      # ----------------------------------------------------
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build Android App Bundle (AAB)
        run: ./gradlew bundleRelease --no-daemon

      # ----------------------------------------------------
      # 5. DEPLOY TO GOOGLE PLAY STORE
      # ----------------------------------------------------
      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SA_KEY }}
          packageName: com.yourcompany.yourapp  # <-- Replace with your actual package name
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal  # options: internal | alpha | beta | production
          status: completed
